name: weiboHotSearch

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0/20 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      TZ: Asia/Shanghai # 时区

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: 'Working'
        run: python ./main.py
        
      - name: Commit files
        run: |
         git config --local user.email "1923029218@qq.com"
         git config --local user.name "LQYHYQ"
         git add .
         git commit -m "update All"
      
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: master
